=head0 *Preface

I<Modern Perl> est un moyen de décrirer la façon dont les programmeurs en Perl 5 les
plus efficaces du monde travaillent. Ils utilisent des idiomes du langage. Ils tirent 
partie de CPAN. Ils font preuve de bon goût et d'astuce pour écrire du code puissant,
maintenable, capable de monter en charge, concis et efficace. Vous aussi, vous pouvez
acquérir ces aptitudes !

Perl a d'abord fait son apparition en 1897 en tant que simple outil pour l'administration
système. Bien qu'il débuta en déclarant et en occupant une niche confortable entre l'écriture de
script shell et la programmation C, il est devenu un langage puissant et généraliste.
Perl 5 possède une solide histoire de pragmatisme et un avenir brillant fait d'affinage
et d'améliorationN<Perl 6 est une réinvention de la programmation s'appuyant sur
les principes de Perl, mais ceci serait le sujet d'un autre livre.>.

Durant la longue histoire de Perl - spécialement les 17 années de Perl 5 - notre
compréhension de ce qui fait de remarquables programmes Perl a changé. Bien que 
vous puissiez écrire des programmes productifs sans jamais tirer parti de tout ce
que le langage offre, la communauté Perl dans son ensemble a inventé, emprunté,
amélioré et affiné des idées et les a rendues disponibles pour quiconque souhaite
les apprendre.

=head1 Exécuter Modern Perl

Le module C<Modern::Perl> de CPAN (L<cpan>) demande à Perl de signaler les constructions
douteuses et les fautes de frappe et active les nouvelles fonctionnalités introduites dans
les versions modernes de Perl 5. Sauf mention contraire, les extraits de code supposent
toujours l'utilisation du squelette de base de programme suivant :

=begin programlisting

    #!/usr/bin/env perl

    use Modern::Perl 2011;
    use autodie;

=end programlisting

... qui est équivalent à :

=begin programlisting

    #!/usr/bin/env perl

    use 5.012;      # implique "use strict;"
    use warnings;
    use autodie;

=end programlisting

Certains exemples utilisent des fonctions de test telles que C<ok()>, C<like()> et C<is()>
(L<testing>). Ces programmes suivent le canevas suivant :

=begin programlisting

    #!/usr/bin/env perl

    use Modern::Perl;
    B<use Test::More;>

    # code d'exemple ici

    B<realiser_les_tests();>

=end programlisting

Au moment de l'écriture, la famille de version stable de Perl 5 est Perl 5.14.
Les exemples de ce livre fonctionnent mieux avec Perl 5.12.0 ou une version plus
récente. De nombreux exemples fonctionneront avec des versions plus anciennes de Perl 5
après quelques adaptations mineures, mais vous rencontrerez davantage de difficultés
avec toute version plus ancienne que la 5.10.0.

X<Strawberry Perl>
X<ActivePerl>
X<perlbrew>
X<CPAN; C<App::perlbrew>>

Si vous n'avez pas Perl 5 installé (ou si vous avez une vieille version d'installée), vous
pouvez installer une version plus récente vous-même. Pour les utilisateurs de Windows, téléchargez
Strawberry Perl sur U<http://www.strawberryperl.com/> ou ActivePerl sur
U<http://www.activestate.com/activeperl>. Les utilisateurs des autres systèmes
d'exploitation dans lequel Perl 5 est déjà installé (ainsi qu'un compilateur C et d'autres
outils de développement) commenceront pas installer le module CPAN C<App::perlbrew>N<Voir
U<http://search.cpan.org/perldoc?App::perlbrew> for installation
les instructions.>.

C<perlbrew> allows you to install and manage multiple versions of Perl 5. This
allows you to switch between versions of Perl 5 as well as to install Perl 5
and CPAN modules in your home directory without affecting the system's version.
If you've ever had to beg your system administrator for permission to install
software, you know how much easier your life can be now.

=head1 Remerciements

This book would not have been possible without questions, comments,
suggestions, advice, wisdom, and encouragement from many, many people. In
particular, the author and editor thank:

L<credits>

Any remaining errors are the fault of the stubborn author.
