=utf8
=head1 La philosophie de Perl

Perl rend les choses faisables - il est flexible, indulgent et maléable.
Des programmeurs compétents l'utilisent tous les jours pour des tâches 
de tous ordres allant des automatisations en une ligne et jetables à des 
projets de plusieurs années réalisés par de nombreux programmeurs.

Perl est pragmatique. Vous avez le contrôle. Vous décidez comment résoudre vos
problèmes et Perl s'adaptera pour faire ce que vous voulez, avec peu de frustration et 
sans cérémonie.

Perl grandira avec vous. Dans une heure, vous en aurez appris suffisamment pour
écrire de vrais programmes utiles - et vous comprendrez I<comment> le langage
fonctionne et I<pourquoi> il fonctionne de cette façon. Modern Perl tire partie
de cette connaissance et de l'expérience mutualisée de toute la communauté Perl 
pour vous aider à écrire du code maintenable qui fonctionne.

Mais d'abord, vous avez besoin de savoir comment en apprendre plus.

L<perldoc>

L<expressivity>

L<context_philosophy>

L<implicit_ideas>
